name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  android:
    uses: ./.github/workflows/android_build.yml
    with:
      upload-artifacts: true
